package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("Test vk login")
    void generatedTest() {
        step("Open 'https://vk.com'", () -> {
            // todo
        });

        step("Set username 'dj-andrej@saieruhg.ru'", () -> {
            // todo
        });

        step("Set password '123456677890'", () -> {
            // todo
        });

        step("Verify successful authorization as Andrew", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because your test steps contain text 'http...' and the page has &lt;title&gt;")
    @DisplayName("Page title test")
    void titleTest() {
        step("Open url 'https://vk.com'", () ->
            open("https://vk.com"));

        step("Checking that the page title has is 'Herzlich Willkommen | VK'", () -> {
            String expectedTitle = "Herzlich Willkommen | VK";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }
}